# yaml-language-server: $schema=https://raw.githubusercontent.com/phil65/agentpool/refs/heads/main/schema/config-schema.json
mcp_servers:
  - "uvx mcp-server-git"

agents:
  picker:
    type: native
    model: openai:gpt-5-nano
    description: Git commit history explorer
    system_prompt: You are a specialist in looking up git commits using your tools from the current working directory.
    connections:
      - type: node
        name: analyzer

  analyzer:
    type: native
    model: openai:gpt-5-nano
    description: Git commit analyzer
    system_prompt: You are an expert in retrieving and returning information about a specific commit from the current working directory.
