id = "agentpool"
name = "AgentPool"
description = "Pydantic-AI based Multi-Agent Framework with YAML-based Agents, Teams, Workflows & Extended ACP / AGUI integration"
version = "1.15.12"
schema_version = 1
authors = ["Philipp Temminghoff"]
repository = "https://github.com/phil65/agentpool"

[agent_servers.agentpool]
name = "AgentPool"
icon = "./icons/agentpool.svg"

[agent_servers.agentpool.targets.darwin-aarch64]
archive = "https://github.com/phil65/agentpool/releases/download/v2.1.9/agentpool-darwin-aarch64-1.15.12.zip"
cmd = "./agentpool"
args = ["serve-acp"]

[agent_servers.agentpool.targets.darwin-x86_64]
archive = "https://github.com/phil65/agentpool/releases/download/v2.1.9/agentpool-darwin-x86_64-1.15.12.zip"
cmd = "./agentpool"
args = ["serve-acp"]

# [agent_servers.agentpool.targets.linux-aarch64]
# archive = "https://github.com/phil65/agentpool/releases/download/v2.1.9/agentpool-linux-aarch64-1.15.12.zip"
# cmd = "./agentpool"
# args = ["serve-acp"]

[agent_servers.agentpool.targets.linux-x86_64]
archive = "https://github.com/phil65/agentpool/releases/download/v2.1.9/agentpool-linux-x86_64-1.15.12.zip"
cmd = "./agentpool"
args = ["serve-acp"]

# [agent_servers.agentpool.targets.windows-aarch64]
# archive = "https://github.com/phil65/agentpool/releases/download/v2.1.9/agentpool-windows-aarch64-1.15.12.zip"
# cmd = "./agentpool.exe"
# args = ["serve-acp"]

[agent_servers.agentpool.targets.windows-x86_64]
archive = "https://github.com/phil65/agentpool/releases/download/v2.1.9/agentpool-windows-x86_64-1.15.12.zip"
cmd = "./agentpool.exe"
args = ["serve-acp"]
